# https://taskfile.dev
version: '3'

tasks:
  test:
    env:
      RUST_BACKTRACE: full
    cmds:
      - cargo test --verbose
  lint:
    cmds:
      - pre-commit run --all
  render:
    cmds:
      - gomplate -f README.md.tpl -o README.md
      - "echo '{\"headings_level\": 2 }' | gomplate -c .=stdin:///cfg.json -f snippets/reference.md.tpl -o snippets/reference_h2.md"
