# https://taskfile.dev
version: '3'

tasks:
  test:
    env:
      RUST_BACKTRACE: full
    cmds:
      - cargo test --verbose
  lint:
    cmds:
      - pre-commit run --all
  render:
    cmds:
      - gomplate --template heading=snippets/heading.tpl -f README.md.tpl -o README.md
      - "echo '{\"headings_level\": 2 }' | gomplate --template heading=snippets/heading.tpl -c .=stdin:///cfg.json -f snippets/reference.md.tpl -o snippets/reference_h2.md"
      - "echo '{\"headings_level\": 1 }' | gomplate --template heading=snippets/heading.tpl -c .=stdin:///cfg.json -f snippets/docs.md.tpl -o snippets/docs.md"
