name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: pkgxdev/setup@v3
      with:
        +: gomplate.ca
    - name: Set up Rust toolchain
      run: |
        rustup update 1.80.0 stable && rustup default stable
        rustup component add --toolchain 1.80.0 clippy rustfmt
        rustup component add --toolchain stable clippy rustfmt
    - uses: pre-commit/action@v3.0.1
    - name: Lint
      run: task lint
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: task test
    - name: Build docs
      run: |
        task render
        cargo doc --verbose
